language: php 

php: 
 - 5.3
 - 5.4

env:
 - DB=MYSQL CORE_RELEASE=master
 - DB=PGSQL CORE_RELEASE=master
 - DB=SQLITE3 CORE_RELEASE=master
 - PHPCS=1 CORE_RELEASE=master

matrix:
  exclude:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=master
    - php: 5.4
      env: DB=SQLITE3 CORE_RELEASE=master
    - php: 5.4
      env: PHPCS=1 CORE_RELEASE=master
  allow_failures:
    - env: DB=PGSQL CORE_RELEASE=master
    - env: DB=SQLITE3 CORE_RELEASE=master
    - env: PHPCS=1 CORE_RELEASE=master

before_script:
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit cms/tests/

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - 2.4
    - post-2.4
    - translation-staging

notifications:
  irc:
    channels:
     - "irc.freenode.org#silverstripe"
